// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectDAW.Data;

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220125192833_RoleMigration")]
    partial class RoleMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectDAW.Models.Atractie", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OraDeschidere")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("OraInchidere")
                        .HasColumnType("time");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pret")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Atractii");
                });

            modelBuilder.Entity("ProiectDAW.Models.Bilet", b =>
                {
                    b.Property<Guid>("VacantaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtractieID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodBilet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataVizita")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VacantaID", "AtractieID");

                    b.HasIndex("AtractieID");

                    b.ToTable("Bilete");
                });

            modelBuilder.Entity("ProiectDAW.Models.Cazare", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Pret")
                        .HasColumnType("real");

                    b.Property<string>("TipCazare")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Cazari");
                });

            modelBuilder.Entity("ProiectDAW.Models.Facilitate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Facilitati");
                });

            modelBuilder.Entity("ProiectDAW.Models.Fotografie", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titlu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UtilizatorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UtilizatorID");

                    b.ToTable("Fotografii");
                });

            modelBuilder.Entity("ProiectDAW.Models.Pachet", b =>
                {
                    b.Property<Guid>("CazareID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FacilitateID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CazareID", "FacilitateID");

                    b.HasIndex("FacilitateID");

                    b.ToTable("Pachete");
                });

            modelBuilder.Entity("ProiectDAW.Models.Portofel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<float>("Suma")
                        .HasColumnType("real");

                    b.Property<Guid>("UtilizatorID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("UtilizatorID")
                        .IsUnique();

                    b.ToTable("Portofel");
                });

            modelBuilder.Entity("ProiectDAW.Models.Rezervare", b =>
                {
                    b.Property<Guid>("VacantaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UtilizatorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataRezervare")
                        .HasColumnType("Date");

                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VacantaID", "UtilizatorID");

                    b.HasIndex("UtilizatorID");

                    b.ToTable("Rezervari");
                });

            modelBuilder.Entity("ProiectDAW.Models.RezervareCazare", b =>
                {
                    b.Property<Guid>("VacantaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CazareID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodRezervare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPlecare")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DataSosire")
                        .HasColumnType("Date");

                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VacantaID", "CazareID");

                    b.HasIndex("CazareID");

                    b.ToTable("RezervariCazari");
                });

            modelBuilder.Entity("ProiectDAW.Models.Utilizator", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("ProiectDAW.Models.Vacanta", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DataSfarsit")
                        .HasColumnType("Date");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tara")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Vacante");
                });

            modelBuilder.Entity("ProiectDAW.Models.Bilet", b =>
                {
                    b.HasOne("ProiectDAW.Models.Atractie", "Atractie")
                        .WithMany("Bilet")
                        .HasForeignKey("AtractieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.Vacanta", "Vacanta")
                        .WithMany("Bilet")
                        .HasForeignKey("VacantaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atractie");

                    b.Navigation("Vacanta");
                });

            modelBuilder.Entity("ProiectDAW.Models.Fotografie", b =>
                {
                    b.HasOne("ProiectDAW.Models.Utilizator", "Utilizator")
                        .WithMany("Fotografie")
                        .HasForeignKey("UtilizatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("ProiectDAW.Models.Pachet", b =>
                {
                    b.HasOne("ProiectDAW.Models.Cazare", "Cazare")
                        .WithMany("Pachet")
                        .HasForeignKey("CazareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.Facilitate", "Facilitate")
                        .WithMany("Pachet")
                        .HasForeignKey("FacilitateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cazare");

                    b.Navigation("Facilitate");
                });

            modelBuilder.Entity("ProiectDAW.Models.Portofel", b =>
                {
                    b.HasOne("ProiectDAW.Models.Utilizator", "Utilizator")
                        .WithOne("Portofel")
                        .HasForeignKey("ProiectDAW.Models.Portofel", "UtilizatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("ProiectDAW.Models.Rezervare", b =>
                {
                    b.HasOne("ProiectDAW.Models.Utilizator", "Utilizator")
                        .WithMany("Rezervare")
                        .HasForeignKey("UtilizatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.Vacanta", "Vacanta")
                        .WithMany("Rezervare")
                        .HasForeignKey("VacantaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");

                    b.Navigation("Vacanta");
                });

            modelBuilder.Entity("ProiectDAW.Models.RezervareCazare", b =>
                {
                    b.HasOne("ProiectDAW.Models.Cazare", "Cazare")
                        .WithMany("RezervareCazare")
                        .HasForeignKey("CazareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProiectDAW.Models.Vacanta", "Vacanta")
                        .WithMany("RezervareCazare")
                        .HasForeignKey("VacantaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cazare");

                    b.Navigation("Vacanta");
                });

            modelBuilder.Entity("ProiectDAW.Models.Atractie", b =>
                {
                    b.Navigation("Bilet");
                });

            modelBuilder.Entity("ProiectDAW.Models.Cazare", b =>
                {
                    b.Navigation("Pachet");

                    b.Navigation("RezervareCazare");
                });

            modelBuilder.Entity("ProiectDAW.Models.Facilitate", b =>
                {
                    b.Navigation("Pachet");
                });

            modelBuilder.Entity("ProiectDAW.Models.Utilizator", b =>
                {
                    b.Navigation("Fotografie");

                    b.Navigation("Portofel");

                    b.Navigation("Rezervare");
                });

            modelBuilder.Entity("ProiectDAW.Models.Vacanta", b =>
                {
                    b.Navigation("Bilet");

                    b.Navigation("Rezervare");

                    b.Navigation("RezervareCazare");
                });
#pragma warning restore 612, 618
        }
    }
}
